### ISSUE TITLE
Consider removing content negotiation

### ISSUE THREAD

**Issue by jyasskin** [wpack-wg/bundled-responses#2]
Moved from @littledan's https://github.com/WICG/webpackage/issues/612:

It's more efficient to use content negotiation to select which bundle to serve, rather than including several variants of a resource inside a bundle. Even most use cases around re-sharing bundles while offline can get away with including a single least-common-denominator resource. I only know of the case of **translations** that concretely need several variants of the same resource.

Can we simplify the design by omitting content negotiation? We'd lose some fidelity in representing HTTP, but that might be acceptable.

**Comment by hayatoito** [comment]
I"m fine to remove the *variants* support from the bundle format, however, I'm wondering how removing the *variants* support impacts on the chromium's implementation. We should align somehow.

@horo-t @irori
Do you know any use case of *variants*? Can we remove *variants* support from the bundle format without any impacts on the chromium?

**Comment by irori** [comment]
Chromium supports _variants_ in Navigation to Web Bundles (https://crbug.com/1029406), but not in Subresource loading with Web Bundles.

Since Navigation to Web Bundles hasn't shipped yet, I think it's fine to remove it from Chromium.

**Comment by horo-t** [comment]
If we remove the content negotiation, it may become difficult to support new data formats like WebP in future. But removing it from the bundle format now and re-thinking when it will be more important sounds acceptable.

**Comment by littledan** [comment]
The idea here is that you would negotiate for the whole bundle, not for resources within the bundle. I think this could permit upgrade to new image formats over time, without shipping all the different options redundantly to the client.

**Comment by hayatoito** [comment]
I think we can close this issue. Content negotiation was already dropped.
